### ISSUE TITLE
Enhancement: Moving all events and the controller into a controller Object

### ISSUE THREAD

**Issue by danjford** [lodestarjs/lodestar-ractive#25]
### Proposal

**First up, I will implement this change on my own branch but will merge it into upstream after a day depending on the feedback from this issue. If this is an accepted enhancement then it will be in the 1.1.0 release along with all of the new enhancements coming in the [lodestar-router](https://github.com/lodestarjs/lodestar-router/issues)**

All though this is a big change early on I think that is an important one. At the moment, everything is declared on the route without clear separation. I think that the current way that is was more of a mistake than intentional.

I think that it should be set up so that the route defines:
- View
- Path
- Controller

And that the controller will contain everything that adds control to your page.
### End Result

Ideally, I think that we could then make it so that controllers are separated even further into separate files, but this is how it would basically look:

```
var App = new LodeRactive();

App.createRoute({
  path: '/',
  controller: {
    controller: function() { }
    actions: {},
    observe: {}
  },
  view: { }
});
```

If you have any comments for or against this or any suggested improvements, then that would be great!

**Comment by xCausxn** [comment]
I think this would be a good enhancement, as breaking it down into separate files will make the workflow easier to manage. Also it means you could potentially not need a controller if you are only looking for basic routing. I do like this concept as the router routes, the controller controls
